export const VIEW_LOGIN_ID = "username"
export const VIEW_PASS_ID = "password"
export const VIEW_OTP_ID = "otp-input"
export const VIEW_SET_OTP_INPUT_ID = "totp"
export const VIEW_SET_OTP_FORM_ID = "kc-totp-settings-form"
export const VIEW_OTP_QR_CODE_ID = "kc-totp-secret-qr-code"
export const VIEW_OTP_CONFIG_ID = "totp"
export const VIEW_LOGIN_BTN_ID = "kc-login"
